### ISSUE TITLE
React hooks integration

### ISSUE THREAD

**Issue by grigio** [EOSIO/ual-reactjs-renderer#41]
Are there some guidelines about how it can be integrated with React Hooks?

**Comment by nasser85** [comment]
Integrating *UAL ReactJS Renderer* with React Hooks should be fairly straightforward since we export the [UALContext](https://github.com/EOSIO/ual-reactjs-renderer/blob/master/src/components/provider/UALContext.js#L3) to the developer.

For example you can return a [Context.Consumer](https://reactjs.org/docs/context.html#contextconsumer) of UAL in a React Function Component.  Within the consumer you can use React.useEffect to subscribe to a successfully authenticated user event via UAL's context.

```javascript
import React, { useState, useEffect } from 'react'
import { UALContext } from 'ual-reactjs-renderer'

export const MyFunctionComponent = (props, context) => {
  const [loggedIn, setLoggedIn] = useState(false)
  const { activeUser } = context
   useEffect(() => {
    if (activeUser) {
      setLoggedIn(true)
    }
  }, [activeUser])
  return <p>{loggedIn ? 'logged in' : 'no logged in'}</p>
}

MyFunctionComponent.contextType = UALContext
```

**Comment by nasser85** [comment]
Closing and marking as resolved.

**Comment by kevinwolfcr** [comment]
You can also `useContext` to avoid using legacy `contextType` static.
